services:
  postgres:
    image: postgres:16-alpine
    container_name: content-cat-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: contentcat
      POSTGRES_PASSWORD: contentcat123
      POSTGRES_DB: contentcat
    ports:
      - "5499:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
